name: Deploy
on: 
  push: 
    branches: ['main']

env:
  NODE_VERSION: 20

jobs: 
  Initialize: 
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ env.VERSION }}

    steps: 
      - name: Set Version
        uses: Nyffels-IT/github-actions-calver-version-generator@v1.0.1

      - name: Current version 
        run: 'echo version: ${{ env.Version }}'

  Build_And_Push: 
    runs-on: ubuntu-latest
    needs: initialize

    steps: 
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Compile - Install
        run: |
          npm ci --prefix /docker-monitor-install
          npm run build--prefix /docker-monitor-install

      - name: Compile - Notifications
        run: |
          npm ci --prefix /docker-monitor-notifications
          npm run build--prefix /docker-monitor-notifications

      - name: Compile - Stats
        run: |
          npm ci --prefix /docker-monitor-stats
          npm run build--prefix /docker-monitor-stats
      
      - name: Prepare for docker 
        run: npx gulp
          
      - name: Set up QEMU
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}       

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: nyffelsit/docker-monitor:${{ needs.initialize.outputs.version }}                   